name: easy_nodes
version: 1.0.2
description: A Flutter library for creating visual node-based editors with draggable, connectable nodes.
repository: https://github.com/tonis2/node-editor
homepage: https://github.com/tonis2/node-editor

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.2
  flutter:
    sdk: flutter
  vector_math: ^2.2.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
